_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "/data/cjh_datasets/coco_weights/faster_rcnn_r50_fpn_3x.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: 540
  MIN_SIZE_TEST: 540
DATASETS:
#  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
#  TEST: ('voc_2007_test',)
  TRAIN: ('coco_uavdt_train',)
  TEST: ('coco_uavdt_test',)
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
#  STEPS: (210000, 250000)
#  MAX_ITER: 270000
  WARMUP_ITERS: 1000
