_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "/data/cjh_datasets/coco_weights/mobilenet_v2.pth"
#  WEIGHTS: "/data/cjh_datasets/mobilenet_coco_pretrain_1/model_final.pth"
  MASK_ON: False
  RETINANET:
    NUM_CLASSES: 80
INPUT:

  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640)
  MIN_SIZE_TEST: 640

  MAX_SIZE_TRAIN: 854
  MAX_SIZE_TEST: 854

#  MIN_SIZE_TRAIN: (540, 572, 604, 636, 668, 700)
#  MIN_SIZE_TEST: 700
#
#  MAX_SIZE_TRAIN: 1328
#  MAX_SIZE_TEST: 1328

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
#  TRAIN: ('coco_uavdt_train',)
#  TEST: ('coco_uavdt_test',)
SOLVER:
#  STEPS: (60000, 80000)
#  MAX_ITER: 90000
  # 10   0.00625
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WARMUP_ITERS: 1000
