_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "/data/cjh_datasets/model_weights/retinanet_r101_fpn_3x.pkl"
  # WEIGHTS: "/data/cjh_datasets/uavdt_results/uavdt_result_coco_1/model_best.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 3
INPUT:

#  MIN_SIZE_TRAIN: (422, 454, 486, 518, 540)
  MIN_SIZE_TRAIN: (540, 570, 604, 636, 668, 700)

  MIN_SIZE_TEST: 700

  MAX_SIZE_TRAIN: 1328
  MAX_SIZE_TEST: 1328

DATASETS:
#  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
#  TEST: ('voc_2007_test',)
  TRAIN: ('coco_uavdt_train',)
  TEST: ('coco_uavdt_test',)
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
#  STEPS: (210000, 250000)
#  MAX_ITER: 270000
  WARMUP_ITERS: 1000
