_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: 540
  MIN_SIZE_TEST: 540
DATASETS:
#  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
#  TEST: ('voc_2007_test',)
  TRAIN: ('voc_2012_trainval',)
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (75000, 90000)
  MAX_ITER: 100000  # 17.4 epochs
  WARMUP_ITERS: 1000
